# Generated by Django 5.1.3 on 2025-10-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='qr_path',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
